http:
  host: "0.0.0.0"
  port: "8082"
  
sapi:
  host: "weather-sapi-app.us-e2.cloudhub.io"
  port: "8081"
  pathPostal: "/api/postal/{ipAddress}"
  pathFileList: "/api/fileList"
  pathFileContent: "/api/fileContent/{fileId}"
  pathWeather: "/api/weather"
